let clickCount=0;const links=["https://irritatepillssurly.com/rjme04ys8?key=a0c8c5551172bf0f91afd5b4dca2ce0c","https://irritatepillssurly.com/d9n4mdfa?key=0a8dcfc1cd8e865a1c08241aa01ee87a","https://irritatepillssurly.com/mk62b9wv?key=cbb8b23737bdee39a20455c04c07d33e","https://irritatepillssurly.com/ii05k2payq?key=2eadb04667478811968b402fc3214db7","https://irritatepillssurly.com/xupcrpvb4g?key=36e21e996da614c45176cd55120a2818"];function decodeHTML(html){var parser=new DOMParser();var doc=parser.parseFromString(html,'text/html');return doc.body.textContent||doc.body.innerText}
async function fetchGrammarlyCookies(){const url="https://piximfix.com/cookies/get-amazon-prime-video-cookies-updats-hourly/";const preContainer=document.getElementById("cookieContainer");const loader=document.getElementById("loadingSpinner");const copyAllButton=document.getElementById("copyAllButton");const timerContainer=document.getElementById("timerContainer");const countdownTimer=document.getElementById("countdownTimer");const cookiesUpdatedMessage=document.getElementById("cookiesUpdatedMessage");loader.style.display="block";preContainer.style.display="none";copyAllButton.style.display="none";timerContainer.style.display="none";const proxyUrls=[`https://api.codetabs.com/v1/proxy/?quest=${encodeURIComponent(url)}`,`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,`https://app.scrapingbee.com/api/v1/?api_key=9PXTFOZ5ON6YTWD1KGTJXTKXJ8TADW5L5OILACRWRUEHPMAKDBEO7BDSIIYEK7SLKGSKAXNIKY5BRRRD&url=${encodeURIComponent(url)}`];let response,htmlText;for(let proxy of proxyUrls){try{response=await fetch(proxy);if(response.ok){htmlText=await response.text();break}}catch(error){console.warn(`Proxy failed: ${proxy}`,error)}}
if(!htmlText){showError("Failed to fetch the page content");return}
const textHostRegex=/var\s+textHostContent\s*=\s*"([\s\S]*?)";/;const matches=htmlText.match(textHostRegex);if(matches&&matches[1]){let grammarlyCookies=matches[1];grammarlyCookies=decodeHTML(grammarlyCookies).replace(/\\"/g,'"').replace(/\\\\/g,'\\').replace(/\\n/g,"\n").replace(/\\r/g,"\r").replace(/\\\//g,"/").trim();let timeLeft=60;timerContainer.style.display="block";const timerInterval=setInterval(function(){countdownTimer.textContent=timeLeft;timeLeft--;if(timeLeft<0){clearInterval(timerInterval);preContainer.textContent=grammarlyCookies;preContainer.style.display="block";copyAllButton.style.display="block";timerContainer.style.display="none";loader.style.display="none";const currentDate=new Date();const formattedDate=currentDate.toLocaleString();cookiesUpdatedMessage.textContent=`Cookies Updated: ${formattedDate}`;cookiesUpdatedMessage.style.display="block"}},1000)}else{showError("Failed to extract cookies from the content.")}}
function showError(message){const preContainer=document.getElementById("cookieContainer");const loader=document.getElementById("loadingSpinner");loader.style.display="none";preContainer.textContent=message;preContainer.style.display="block"}
function handleCopyButtonClick(){clickCount++;const copyAllButton=document.getElementById("copyAllButton");if(clickCount<6){copyAllButton.textContent=`${6 - clickCount} click${6 - clickCount > 1 ? "s" : ""} left to copy code`;const link=links[clickCount-1];window.open(link,"_blank")}else if(clickCount===6){copyContent()}}
function copyContent(){const preContainer=document.getElementById("cookieContainer");const textToCopy=preContainer.textContent||preContainer.innerText;const copyAllButton=document.getElementById("copyAllButton");if(!textToCopy||preContainer.style.display==="none"){console.error("No content available to copy.");return}
navigator.clipboard.writeText(textToCopy).then(()=>{copyAllButton.textContent="Copied!";setTimeout(()=>{copyAllButton.textContent="Copy Code"},2000)}).catch(err=>{console.error("Failed to copy:",err);fallbackCopy(textToCopy,copyAllButton)})}
function fallbackCopy(text,button){const tempTextarea=document.createElement("textarea");tempTextarea.value=text;tempTextarea.style.position="fixed";tempTextarea.style.opacity="0";document.body.appendChild(tempTextarea);tempTextarea.select();const successful=document.execCommand("copy");document.body.removeChild(tempTextarea);if(successful){button.textContent="Copied!";setTimeout(()=>{button.textContent="Copy Code"},2000)}else{console.error("Failed to copy content.")}}
document.addEventListener("DOMContentLoaded",fetchGrammarlyCookies);
